---
driver: 
  name: vagrant

provisioner:
  name: chef_zero

platforms:
<%
%w(
  debian-7.8
  ubuntu-12.04
  ubuntu-14.04
  centos-6.6
  centos-7.0
).each do |p|
%>
  - name: <%= p %>-chef-11
    driver:
      box: opscode-<%= p %>
    provisioner:
      require_chef_omnibus: 11

  - name: <%= p %>-chef-12
    driver:
      box: opscode-<%= p %>
    provisioner:
      require_chef_omnibus: 12
<% end %>

suites:
  - name: monit-ng-default
    run_list:
      - recipe[monit-ng]
      - recipe[setup]
  - name: monit-ng-source
    run_list:
      - recipe[monit-ng]
      - recipe[setup]
    attributes: { monit: { install_method: source } }
